### ISSUE TITLE
GoogleCode was shut down, shiro-faces maven repository is not available anymore

### ISSUE THREAD

**Issue by pfink** [deluan/shiro-faces#6]
Hi there,
I think the title of this issue tells everything. Currently there is no maven repo for shiro faces...

**Comment by nooone** [comment]
+1

**Comment by thaylongs** [comment]
+1

**Comment by NBAMj** [comment]
+1

**Comment by deluan** [comment]
Deployed it to Bintray: https://bintray.com/deluan/maven/shiro-faces
See the README for new repository configuration.
